### ISSUE TITLE
Add Signup & Login Files

### ISSUE THREAD

**Issue by MohamedHesham96** [MohamedHesham96/Tester-Project#16]

**Comment by MoussaElenany95** [comment]
دوول اهم صفحتين اللي هيتبني عليهم الشغل كله ما اضافوش ليه

**Comment by nahlaFathy** [comment]
3ndy moshkela fl upload msh rady yrfa3 l files
ynfa3 arf3ha .txt msh .php ??

**Comment by nahlaFathy** [comment]
[quiz.txt](https://github.com/MohamedHesham96/Tester-Project/files/923787/quiz.txt)
![back](https://cloud.githubusercontent.com/assets/24443098/25065942/0055ea0a-2219-11e7-81e1-8b463dd1c767.jpg)

[stylesheet.txt](https://github.com/MohamedHesham96/Tester-Project/files/923788/stylesheet.txt)
[stylesheet1.txt](https://github.com/MohamedHesham96/Tester-Project/files/923789/stylesheet1.txt)

**Comment by MohamedHesham96** [comment]
**نهال لازم تضيفي بقيت الحجات الي موجودة في جدول ال
users 
علشان التسجيل يكمل**

**Comment by nahlaFathy** [comment]
ايه بقيت الحاجات دى ؟؟

**Comment by MohamedHesham96** [comment]
منا بقولك شوفيها في جدول ال
users 
هتلاقيها
