### ISSUE TITLE
Add ComboBox

### ISSUE THREAD

**Issue by MohamedHesham96** [MohamedHesham96/Tester-Project#28]
# **Add ComboBox in all pages 
ComboBox Contains : 

1. Username
2. Profile
3. SignOut**

**Comment by MoussaElenany95** [comment]
done :]

**Comment by MohamedHesham96** [comment]
هو انت ضفته فين يا موسى ؟؟ 
انا مش لاقيه !

**Comment by MoussaElenany95** [comment]
اه انا عملته بس ما رفعتوش عشان مش عارف اضيفه فين 😂😂

**Comment by MohamedHesham96** [comment]
تمام .. منطقي بردوه هههههه
